spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: anthropic/claude-3-sonnet
          temperature: 0.7
          maxTokens: 1000

server:
  port: 8080

logging:
  level:
    com.multiagent: DEBUG