spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          maxTokens: 1000

server:
  port: 8080

logging:
  level:
    com.multiagent: DEBUG