spring:
  application:
    name: @project.name@
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: ${OPENROUTER_MODEL:your-model-here}
          temperature: 0.7
          maxTokens: 1000
          http-headers:
            HTTP-Referer: "https://github.com/PisklovCor/mlinside-2025"
            X-Title: "@project.name@ v@project.version@"

server:
  port: 8080

logging:
  level:
    com.multiagent: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.multiagent.controller